import React, { useState } from 'react';
import { Clock, ChefHat, Flame, ChevronDown, ChevronUp, Copy, Download, Check } from 'lucide-react';
import { Recipe } from '../types';

interface RecipeCardProps {
  recipe: Recipe;
  index: number;
}

export const RecipeCard: React.FC<RecipeCardProps> = ({ recipe, index }) => {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const difficultyColor = {
    'Easy': 'text-green-600 bg-green-100',
    'Medium': 'text-yellow-600 bg-yellow-100',
    'Hard': 'text-red-600 bg-red-100',
  }[recipe.difficulty] || 'text-gray-600 bg-gray-100';

  const formatRecipeText = () => {
    return `${recipe.title}
----------------------------------------
${recipe.description}

DETAILS
-------
Difficulty: ${recipe.difficulty}
Prep Time: ${recipe.prepTime}
Cook Time: ${recipe.cookTime}
Calories: ${recipe.calories}

INGREDIENTS
-----------
${recipe.ingredients.map(ing => `• ${ing}`).join('\n')}

INSTRUCTIONS
------------
${recipe.instructions.map((step, i) => `${i + 1}. ${step}`).join('\n')}

Tags: ${recipe.tags.join(', ')}

Generated by Smart Pantry Chef`;
  };

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation();
    try {
      await navigator.clipboard.writeText(formatRecipeText());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleDownload = (e: React.MouseEvent) => {
    e.stopPropagation();
    const text = formatRecipeText();
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${recipe.title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div 
      className="bg-white rounded-2xl shadow-lg overflow-hidden border border-slate-100 hover:shadow-xl transition-all duration-300 flex flex-col h-full"
      style={{ animationDelay: `${index * 100}ms` }}
    >
      <div className="p-6 flex-grow">
        <div className="flex justify-between items-start mb-4">
          <div>
            <div className="flex flex-wrap gap-2 mb-3">
              <span className={`px-2.5 py-0.5 rounded-full text-xs font-semibold uppercase tracking-wide ${difficultyColor}`}>
                {recipe.difficulty}
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold uppercase tracking-wide bg-blue-100 text-blue-600 flex items-center">
                <Flame size={12} className="mr-1" /> {recipe.calories}
              </span>
            </div>
            <h3 className="text-2xl font-bold text-slate-800 leading-tight">{recipe.title}</h3>
          </div>
        </div>

        <p className="text-slate-600 mb-6 italic">{recipe.description}</p>

        <div className="flex items-center space-x-6 text-sm text-slate-500 mb-6 border-t border-b border-slate-100 py-4">
          <div className="flex items-center">
            <ChefHat size={18} className="mr-2 text-emerald-500" />
            <span>Prep: <strong>{recipe.prepTime}</strong></span>
          </div>
          <div className="flex items-center">
            <Clock size={18} className="mr-2 text-emerald-500" />
            <span>Cook: <strong>{recipe.cookTime}</strong></span>
          </div>
        </div>

        <div className="mb-6">
            <h4 className="font-semibold text-slate-800 mb-3 flex items-center">
              Ingredients
            </h4>
            <ul className="space-y-2">
              {recipe.ingredients.slice(0, expanded ? undefined : 4).map((ing, i) => (
                <li key={i} className="flex items-start text-slate-600 text-sm">
                  <span className="w-1.5 h-1.5 bg-emerald-400 rounded-full mt-1.5 mr-2 flex-shrink-0"></span>
                  {ing}
                </li>
              ))}
              {!expanded && recipe.ingredients.length > 4 && (
                <li className="text-xs text-slate-400 pl-3.5 pt-1">
                  + {recipe.ingredients.length - 4} more ingredients...
                </li>
              )}
            </ul>
        </div>
      </div>

      <div className="px-6 pb-6 flex gap-3">
        <button
          onClick={() => setExpanded(!expanded)}
          className="flex-1 py-3 px-4 bg-slate-50 hover:bg-slate-100 text-slate-700 rounded-xl font-medium text-sm flex items-center justify-center transition-colors"
        >
          {expanded ? (
            <>Show Less <ChevronUp size={16} className="ml-2" /></>
          ) : (
            <>View Instructions <ChevronDown size={16} className="ml-2" /></>
          )}
        </button>

        <button
          onClick={handleCopy}
          className={`w-12 h-12 flex flex-shrink-0 items-center justify-center rounded-xl border transition-all duration-200 ${
            copied 
              ? 'bg-green-50 border-green-200 text-green-600' 
              : 'bg-slate-50 border-transparent hover:bg-emerald-50 hover:border-emerald-200 hover:text-emerald-600 text-slate-500'
          }`}
          title="Copy to Clipboard"
        >
          {copied ? <Check size={20} /> : <Copy size={20} />}
        </button>

        <button
          onClick={handleDownload}
          className="w-12 h-12 flex flex-shrink-0 items-center justify-center rounded-xl bg-slate-50 border border-transparent hover:bg-emerald-50 hover:border-emerald-200 hover:text-emerald-600 text-slate-500 transition-all duration-200"
          title="Download Recipe"
        >
          <Download size={20} />
        </button>
      </div>

      {/* Expandable Section */}
      {expanded && (
        <div className="px-6 pb-8 pt-2 bg-slate-50 border-t border-slate-100 animate-slide-down">
          <h4 className="font-semibold text-slate-800 mb-4">Instructions</h4>
          <ol className="space-y-4">
            {recipe.instructions.map((step, i) => (
              <li key={i} className="flex gap-3 text-slate-700 text-sm leading-relaxed">
                <span className="flex-shrink-0 w-6 h-6 rounded-full bg-emerald-500 text-white flex items-center justify-center text-xs font-bold">
                  {i + 1}
                </span>
                <span className="pt-0.5">{step}</span>
              </li>
            ))}
          </ol>
          
          <div className="mt-6 pt-4 border-t border-slate-200">
             <div className="flex flex-wrap gap-2">
                {recipe.tags.map((tag, t) => (
                  <span key={t} className="text-xs text-slate-500 px-2 py-1 bg-white border border-slate-200 rounded-md">
                    #{tag}
                  </span>
                ))}
             </div>
          </div>
        </div>
      )}
    </div>
  );
};